---
- name: add {{ restund_user }} group
  group:
    name: "{{ restund_user }}"
    state: present
    system: true
  when: restund_user != 'root'
  tags:
    - restund

- name: add {{ restund_user }} user
  user:
    name: "{{ restund_user }}"
    shell: "/bin/false"
    group: "{{ restund_user }}"
    system: true
    createhome: false
  when: restund_user != 'root'
  tags:
    - restund

- name: create /etc/restund
  file:
    path: /etc/restund
    state: directory
    mode:  0755
    owner: "{{ restund_user }}"
    group: "{{ restund_user }}"
  tags:
    - restund

- name: install restund tls certificate
  copy:
    dest:    /etc/restund/restund.pem
    content: "{{ restund_tls_certificate }}"
    mode:    0440
    owner:   "{{ restund_user }}"
    group:   "{{ restund_user }}"
  when: restund_tls_certificate is defined
  tags:
    - restund

- name: restund.conf
  template:
    src:   templates/restund.conf.j2
    dest:  /etc/restund/restund.conf
    mode:  0440
    owner: "{{ restund_user }}"
    group: "{{ restund_user }}"
  tags:
    - restund

- name: install restund unit file
  template:
    src:   templates/restund.service.j2
    dest:  /etc/systemd/system/restund.service
    mode:  0644
    owner: root
    group: root
  notify:
    - systemctl daemon-reload
  tags:
    - restund

- service:
    name:    restund
    enabled: true
    state:   started
